server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-curly-sky-atq1oiny-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_BJRNyC90rHxE}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

